
name: naturesync
description: "Never forget to water your green friends. Let us be your plant watering reminder."
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  google_fonts: ^6.2.1
  page_transition: ^2.1.0
  
  lottie: ^3.1.0
  image_picker: ^1.0.7
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  http: ^1.2.1
  tflite_flutter: ^0.10.4
  tflite_flutter_helper_plus: ^0.0.2
  image: ^3.3.0
  ffi: ^2.1.2
  weather: ^3.1.1
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  flutter_lints: ^3.0.1
  riverpod_lint: ^2.3.10
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/appIcon.png
    - assets/appLogo.png
    - assets/appSplash12.png
    - assets/newlogo.jpg
    - assets/model_unquant.tflite
    - assets/labels.txt
    - assets/animations/config.json
    - assets/animations/custom_variable.json
    - assets/animations/name_your_plant.json
    - assets/animations/taking_a_picture.json